In [16]:
# Imports and Paths

import pandas as pd
from pathlib import Path

project_root = Path.cwd().parent
data_dir = project_root / "data"
raw_dir = data_dir / "raw"
processed_dir = data_dir / "processed"
figures_dir = project_root / "figures"

processed_dir.mkdir(parents=True, exist_ok=True)
figures_dir.mkdir(parents=True, exist_ok=True)

In [17]:
# Drug File: Inspect

drug_path = raw_dir / "drug.csv"

# Load just enough to see column names
df_drug_sample = pd.read_csv(drug_path, nrows=5)
df_drug_sample.columns.tolist()

['DATASET',
 'NLME_RESULT_ID',
 'NLME_CURVE_ID',
 'CELL_LINE_NAME',
 'SANGER_MODEL_ID',
 'CANCER_TYPE',
 'DRUG_ID',
 'DRUG_NAME',
 'PUTATIVE_TARGET',
 'PATHWAY_NAME',
 'MIN_CONC',
 'MAX_CONC',
 'LN_IC50',
 'AUC',
 'RMSE',
 'Z_SCORE']

In [18]:
# Drug File: Rename
df_drug = pd.read_csv(drug_path)

df_drug = df_drug.rename(columns={
    "DRUG_NAME": "drug_name",
    "SANGER_MODEL_ID": "model_id",
    "LN_IC50": "ln_ic50"
})

df_drug[["drug_name", "model_id", "ln_ic50"]].head()

      drug_name   model_id   ln_ic50
0  Camptothecin  SIDM01132 -1.463887
1  Camptothecin  SIDM00848 -4.869455
2  Camptothecin  SIDM00263 -3.360586
3  Camptothecin  SIDM00269 -5.044940
4  Camptothecin  SIDM00203 -3.741991

In [19]:
# Expression File: Inspect a Sample and Standardize Names

expr_path = raw_dir / "expr.csv"

df_expr_sample = pd.read_csv(expr_path, nrows=5)
df_expr_sample.columns.tolist()

['dataset_id',
 'model_id',
 'gene_id',
 'gene_symbol',
 'ensembl_gene_id',
 'model_name',
 'htseq_read_count',
 'rsem_expected_count',
 'rsem_fpkm',
 'rsem_tpm',
 'htseq_fpkm',
 'data_source',
 'duplicate']

In [20]:
# Get Models of Interest (Cisplatin)

drug_col = "drug_name"
model_col = "model_id"
response_col = "ln_ic50"

df_cis = df_drug[df_drug[drug_col] == "Cisplatin"].copy()
df_cis = df_cis[[model_col, drug_col, response_col]].dropna()

models_of_interest = set(df_cis[model_col].unique())
assert df_cis[model_col].is_unique
len(models_of_interest), df_cis.head()

(760,
        model_id  drug_name   ln_ic50
 1709  SIDM01132  Cisplatin  3.168266
 1710  SIDM00848  Cisplatin -0.007561
 1711  SIDM00269  Cisplatin  0.045420
 1712  SIDM00203  Cisplatin  0.923136
 1713  SIDM01111  Cisplatin -0.134330)

In [6]:
# Chunk‑Load Expression

value_col_original = "rsem_tpm"

chunks = []
total_rows = 0
kept_rows = 0

for i, chunk in enumerate(pd.read_csv(
    expr_path,
    chunksize=50_000,
    usecols=["model_id", "gene_symbol", value_col_original])):

  # Rename columns inside chunk
    chunk = chunk.rename(columns={
        value_col_original: "expr_value",
    })

    total_rows += len(chunk)

    # Filter to models of interest
    chunk = chunk[chunk["model_id"].isin(models_of_interest)]
    kept_rows += len(chunk)

    if not chunk.empty:
        chunks.append(chunk)

    # Progress message every few chunks
    if i % 10 == 0:
        print(f"Chunk {i}: total_rows={total_rows}, kept_rows={kept_rows}")

df_expr_small = pd.concat(chunks, ignore_index=True)

df_expr_small.head()

Chunk 0: total_rows=50000, kept_rows=18742
Chunk 10: total_rows=550000, kept_rows=206164
Chunk 20: total_rows=1050000, kept_rows=393616
Chunk 30: total_rows=1550000, kept_rows=581088
Chunk 40: total_rows=2050000, kept_rows=768546
Chunk 50: total_rows=2550000, kept_rows=955974
Chunk 60: total_rows=3050000, kept_rows=1143411
Chunk 70: total_rows=3550000, kept_rows=1330876
Chunk 80: total_rows=4050000, kept_rows=1518352
Chunk 90: total_rows=4550000, kept_rows=1705752
Chunk 100: total_rows=5050000, kept_rows=1893225
Chunk 110: total_rows=5550000, kept_rows=2080681
Chunk 120: total_rows=6050000, kept_rows=2268121
Chunk 130: total_rows=6550000, kept_rows=2455568
Chunk 140: total_rows=7050000, kept_rows=2643028
Chunk 150: total_rows=7550000, kept_rows=2830454
Chunk 160: total_rows=8050000, kept_rows=3017925
Chunk 170: total_rows=8550000, kept_rows=3205347
Chunk 180: total_rows=9050000, kept_rows=3392824
Chunk 190: total_rows=9550000, kept_rows=3580266
Chunk 200: total_rows=10050000, kept_rows=3767694
Chunk 210: total_rows=10550000, kept_rows=3955146
Chunk 220: total_rows=11050000, kept_rows=4142585
Chunk 230: total_rows=11550000, kept_rows=4330069
Chunk 240: total_rows=12050000, kept_rows=4517498
Chunk 250: total_rows=12550000, kept_rows=4704940
Chunk 260: total_rows=13050000, kept_rows=4892374
Chunk 270: total_rows=13550000, kept_rows=5079833
Chunk 280: total_rows=14050000, kept_rows=5267272
Chunk 290: total_rows=14550000, kept_rows=5454713
Chunk 300: total_rows=15050000, kept_rows=5642192
Chunk 310: total_rows=15550000, kept_rows=5829634
Chunk 320: total_rows=16050000, kept_rows=6017082
Chunk 330: total_rows=16550000, kept_rows=6204531
Chunk 340: total_rows=17050000, kept_rows=6391959
Chunk 350: total_rows=17550000, kept_rows=6579440
Chunk 360: total_rows=18050000, kept_rows=6766878
Chunk 370: total_rows=18550000, kept_rows=6954312
Chunk 380: total_rows=19050000, kept_rows=7141762
Chunk 390: total_rows=19550000, kept_rows=7329205
Chunk 400: total_rows=20050000, kept_rows=7516679
Chunk 410: total_rows=20550000, kept_rows=7704123
Chunk 420: total_rows=21050000, kept_rows=7891570
Chunk 430: total_rows=21550000, kept_rows=8079006
Chunk 440: total_rows=22050000, kept_rows=8266466
Chunk 450: total_rows=22550000, kept_rows=8453875
Chunk 460: total_rows=23050000, kept_rows=8641346
Chunk 470: total_rows=23550000, kept_rows=8828806
Chunk 480: total_rows=24050000, kept_rows=9016248
Chunk 490: total_rows=24550000, kept_rows=9203680
Chunk 500: total_rows=25050000, kept_rows=9391138
Chunk 510: total_rows=25550000, kept_rows=9578600
Chunk 520: total_rows=26050000, kept_rows=9766059
Chunk 530: total_rows=26550000, kept_rows=9953486
Chunk 540: total_rows=27050000, kept_rows=10140924
Chunk 550: total_rows=27550000, kept_rows=10328383
Chunk 560: total_rows=28050000, kept_rows=10515812
Chunk 570: total_rows=28550000, kept_rows=10703276
Chunk 580: total_rows=29050000, kept_rows=10890744
Chunk 590: total_rows=29550000, kept_rows=11078186
Chunk 600: total_rows=30050000, kept_rows=11265611
Chunk 610: total_rows=30550000, kept_rows=11453093
Chunk 620: total_rows=31050000, kept_rows=11640524
Chunk 630: total_rows=31550000, kept_rows=11827976
Chunk 640: total_rows=32050000, kept_rows=12015434
Chunk 650: total_rows=32550000, kept_rows=12202859
Chunk 660: total_rows=33050000, kept_rows=12390305
Chunk 670: total_rows=33550000, kept_rows=12577748
Chunk 680: total_rows=34050000, kept_rows=12765235
Chunk 690: total_rows=34550000, kept_rows=12952652
Chunk 700: total_rows=35050000, kept_rows=13140082
Chunk 710: total_rows=35550000, kept_rows=13327535
Chunk 720: total_rows=36050000, kept_rows=13515002
Chunk 730: total_rows=36550000, kept_rows=13702460
Chunk 740: total_rows=37050000, kept_rows=13889893
Chunk 750: total_rows=37550000, kept_rows=14077350
Chunk 760: total_rows=38050000, kept_rows=14264808
Chunk 770: total_rows=38550000, kept_rows=14452265
Chunk 780: total_rows=39050000, kept_rows=14639693
Chunk 790: total_rows=39550000, kept_rows=14827131
Chunk 800: total_rows=40050000, kept_rows=15014593
Chunk 810: total_rows=40550000, kept_rows=15202041
Chunk 820: total_rows=41050000, kept_rows=15389503
Chunk 830: total_rows=41550000, kept_rows=15576928
Chunk 840: total_rows=42050000, kept_rows=15764374
Chunk 850: total_rows=42550000, kept_rows=15951812
Chunk 860: total_rows=43050000, kept_rows=16139268
Chunk 870: total_rows=43550000, kept_rows=16326717
Chunk 880: total_rows=44050000, kept_rows=16516012
Chunk 890: total_rows=44550000, kept_rows=16848377
Chunk 900: total_rows=45050000, kept_rows=17080883
Chunk 910: total_rows=45550000, kept_rows=17461748
Chunk 920: total_rows=46050000, kept_rows=17843299
Chunk 930: total_rows=46550000, kept_rows=18139685
Chunk 940: total_rows=47050000, kept_rows=18481874
Chunk 950: total_rows=47550000, kept_rows=18753073
Chunk 960: total_rows=48050000, kept_rows=18896432
Chunk 970: total_rows=48550000, kept_rows=19276123
Chunk 980: total_rows=49050000, kept_rows=19693879
Chunk 990: total_rows=49550000, kept_rows=19947147
Chunk 1000: total_rows=50050000, kept_rows=20302182
Chunk 1010: total_rows=50550000, kept_rows=20635213
Chunk 1020: total_rows=51050000, kept_rows=21081253
Chunk 1030: total_rows=51550000, kept_rows=21494303
Chunk 1040: total_rows=52050000, kept_rows=21809827
Chunk 1050: total_rows=52550000, kept_rows=22187206
Chunk 1060: total_rows=53050000, kept_rows=22576919
Chunk 1070: total_rows=53550000, kept_rows=22960219
Chunk 1080: total_rows=54050000, kept_rows=23336853
Chunk 1090: total_rows=54550000, kept_rows=23711544
Chunk 1100: total_rows=55050000, kept_rows=24016080
Chunk 1110: total_rows=55550000, kept_rows=24312289
Chunk 1120: total_rows=56050000, kept_rows=24596657
Chunk 1130: total_rows=56550000, kept_rows=24792753
Chunk 1140: total_rows=57050000, kept_rows=25088304
Chunk 1150: total_rows=57550000, kept_rows=25327800
Chunk 1160: total_rows=58050000, kept_rows=25700178
Chunk 1170: total_rows=58550000, kept_rows=26150851
Chunk 1180: total_rows=59050000, kept_rows=26445241
Chunk 1190: total_rows=59550000, kept_rows=26786565
Chunk 1200: total_rows=60050000, kept_rows=27116964
Chunk 1210: total_rows=60550000, kept_rows=27410655
Chunk 1220: total_rows=61050000, kept_rows=27871918
Chunk 1230: total_rows=61550000, kept_rows=28266845
Chunk 1240: total_rows=62050000, kept_rows=28421899
Chunk 1250: total_rows=62550000, kept_rows=28812207
Chunk 1260: total_rows=63050000, kept_rows=29213309
Chunk 1270: total_rows=63550000, kept_rows=29614090
Chunk 1280: total_rows=64050000, kept_rows=30015505
Chunk 1290: total_rows=64550000, kept_rows=30416893
Chunk 1300: total_rows=65050000, kept_rows=30818756
Chunk 1310: total_rows=65550000, kept_rows=31219944
Chunk 1320: total_rows=66050000, kept_rows=31621085
Chunk 1330: total_rows=66550000, kept_rows=32022141
Chunk 1340: total_rows=67050000, kept_rows=32423590
Chunk 1350: total_rows=67550000, kept_rows=32824484
Chunk 1360: total_rows=68050000, kept_rows=33225909
Chunk 1370: total_rows=68550000, kept_rows=33416189
Chunk 1380: total_rows=69050000, kept_rows=33431955
Chunk 1390: total_rows=69550000, kept_rows=33457179
Chunk 1400: total_rows=70050000, kept_rows=33468934
Chunk 1410: total_rows=70550000, kept_rows=33468934
Chunk 1420: total_rows=71050000, kept_rows=33468934
Chunk 1430: total_rows=71550000, kept_rows=33468934
Chunk 1440: total_rows=72050000, kept_rows=33468934
Chunk 1450: total_rows=72550000, kept_rows=33468934
Chunk 1460: total_rows=73050000, kept_rows=33468934
Chunk 1470: total_rows=73550000, kept_rows=33468934
Chunk 1480: total_rows=74050000, kept_rows=33468934
Chunk 1490: total_rows=74550000, kept_rows=33468934
Chunk 1500: total_rows=75050000, kept_rows=33468934
Chunk 1510: total_rows=75550000, kept_rows=33468934
Chunk 1520: total_rows=76050000, kept_rows=33468934
Chunk 1530: total_rows=76550000, kept_rows=33468934
Chunk 1540: total_rows=77050000, kept_rows=33468934
Chunk 1550: total_rows=77550000, kept_rows=33468934
Chunk 1560: total_rows=78050000, kept_rows=33468934
Chunk 1570: total_rows=78550000, kept_rows=33468934

    model_id gene_symbol  expr_value
0  SIDM00776        DVL2      3.5521
1  SIDM00437       STPG1      2.2898
2  SIDM00598       STPG1      2.9486
3  SIDM00657       STPG1      1.3674
4  SIDM00506       STPG1      4.4874

In [7]:
# Save filtered table

reduced_expr_path = processed_dir / "rnaseq_expression_cisplatin_models.csv"
df_expr_small.to_csv(reduced_expr_path, index=False)
reduced_expr_path

WindowsPath('C:/Users/draar/gdsc-drug-response-project/data/processed/rnaseq_expression_cisplatin_models.csv')

In [12]:
# Reload filtered table (you can restart the notebook from here without redoing the chunk-loading)

df_expr_small = pd.read_csv(processed_dir / "rnaseq_expression_cisplatin_models.csv")

In [13]:
# Pivot expression to wide format and merge

df_expr_wide = (
    df_expr_small.pivot_table(
        index=model_col,
        columns="gene_symbol",
        values="expr_value",
        aggfunc="mean"
    ).reset_index()
)

df_expr_wide.shape, df_expr_wide.head()

((743, 41144),
 gene_symbol   model_id    A1BG  A1BG-AS1    A1CF     A2M  A2M-AS1   A2ML1  \
 0            SIDM00003  3.9736    3.1408  0.0144  4.1326   0.4114  0.0000
 1            SIDM00042  0.5059    0.8639  0.0566  0.2265   1.3561  0.4542
 2            SIDM00044  5.3125    3.5398  0.0144  0.0000   0.0144  0.0000
 3            SIDM00045  0.0976    0.1890  2.9982  0.0000   0.0286  0.0000
 4            SIDM00047  2.9782    1.5211  0.0144  0.0000   1.1375  0.0841

 gene_symbol  A2ML1-AS1  A2ML1-AS2   A2MP1  ...    ZXDA    ZXDB    ZXDC  \
 0                  0.0        0.0  0.0000  ...  1.0909  2.1010  4.0488
 1                  0.0        0.0  0.0286  ...  1.2630  2.5008  4.7840
 2                  0.0        0.0  0.0566  ...  1.1177  2.2780  4.2787
 3                  0.0        0.0  0.0000  ...  1.5945  3.7761  5.0781
 4                  0.0        0.0  0.0000  ...  1.2690  2.3646  3.9079

 gene_symbol  ZYG11A  ZYG11AP1  ZYG11B     ZYX  ZYXP1   ZZEF1    ZZZ3
 0            2.6369    0.0976  3.7148  6.9590    0.0  4.3561  5.5622
 1            0.0704    0.0000  2.3813  5.0112    0.0  4.1465  4.2615
 2            1.0286    0.0000  4.0072  7.9930    0.0  3.7887  5.7960
 3            0.0426    0.0000  3.2750  6.0892    0.0  3.4209  5.1445
 4            0.3334    0.0000  3.4249  6.5437    0.0  3.3730  4.6047

 [5 rows x 41144 columns])

In [14]:
# Merge with Cisplatin response

df_merged = pd.merge(
    df_cis,
    df_expr_wide,
    how="inner",
    on=model_col
)

df_merged.shape, df_merged.head()

((743, 41146),
     model_id  drug_name   ln_ic50     A1BG  A1BG-AS1    A1CF      A2M  \
 0  SIDM01132  Cisplatin  3.168266  5.18545    2.9833  0.0000  0.52325
 1  SIDM00848  Cisplatin -0.007561  4.86890    3.4476  0.0000  1.99640
 2  SIDM00269  Cisplatin  0.045420  4.54970    3.8001  0.0841  3.21570
 3  SIDM00203  Cisplatin  0.923136  4.22500    3.2095  0.0144  0.50590
 4  SIDM01111  Cisplatin -0.134330  4.49250    2.8115  0.0144  0.47510

    A2M-AS1   A2ML1  A2ML1-AS1  ...     ZXDA     ZXDB     ZXDC  ZYG11A  \
 0   0.0000  0.0213        0.0  ...  0.31285  1.60475  3.10825  0.6801
 1   0.1243  3.1890        0.0  ...  1.68260  2.33060  5.18630  0.0841
 2   0.0566  0.5753        0.0  ...  2.82980  3.41280  6.78270  2.3190
 3   0.0976  2.8156        0.0  ...  2.49570  3.47640  5.30710  3.0321
 4   0.0286  0.5558        0.0  ...  1.28690  2.26000  4.94810  2.7634

    ZYG11AP1   ZYG11B      ZYX  ZYXP1    ZZEF1    ZZZ3
 0       0.0  2.58955  5.95435    0.0  3.47415  4.0301
 1       0.0  3.09930  5.52420    NaN  3.60640  4.5211
 2       0.0  4.21410  9.01050    0.0  4.93400  5.4561
 3       0.0  4.47310  6.95290    0.0  4.35900  5.3366
 4       0.0  3.20950  3.99550    NaN  4.02240  4.9635

 [5 rows x 41146 columns])

In [15]:
# Save for later notebooks

out_path = processed_dir / "cisplatin_rnaseq_modelready.csv"
print("Saving to:", out_path)
df_merged.to_csv(out_path, index=False)

Saving to: C:\Users\draar\gdsc-drug-response-project\data\processed\cisplatin_rnaseq_modelready.csv