In [15]:
# Imports and Paths
from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path
import pandas as pd

base_dir = Path("/content/drive/MyDrive/gdsc-drug-response")

raw_dir      = base_dir / "raw"
processed_dir = base_dir / "processed"
processed_dir.mkdir(parents=True, exist_ok=True)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [16]:
# Drug File: Inspect and Rename

drug_path = raw_dir / "drug.csv"

# Load just enough to see column names
df_drug_sample = pd.read_csv(drug_path, nrows=5)
df_drug_sample.columns.tolist()

df_drug = pd.read_csv(drug_path)

df_drug = df_drug.rename(columns={
    "DRUG_NAME": "drug_name",        # replace key with actual name
    "SANGER_MODEL_ID": "model_id",   # replace if needed
    "LN_IC50": "ln_ic50"             # replace if needed
})

df_drug[["drug_name", "model_id", "ln_ic50"]].head()

      drug_name   model_id   ln_ic50
0  Camptothecin  SIDM01132 -1.463887
1  Camptothecin  SIDM00848 -4.869455
2  Camptothecin  SIDM00263 -3.360586
3  Camptothecin  SIDM00269 -5.044940
4  Camptothecin  SIDM00203 -3.741991

In [17]:
# Expression File: Inspect a Sample and Standardize Names

expr_path = raw_dir / "expr.csv"

df_expr_sample = pd.read_csv(expr_path, nrows=5)
df_expr_sample.columns.tolist()

['dataset_id',
 'model_id',
 'gene_id',
 'gene_symbol',
 'ensembl_gene_id',
 'model_name',
 'htseq_read_count',
 'rsem_expected_count',
 'rsem_fpkm',
 'rsem_tpm',
 'htseq_fpkm',
 'data_source',
 'duplicate']

In [18]:
# Get Models of Interest (Fulvestrant)

drug_col = "drug_name"
model_col = "model_id"
response_col = "ln_ic50"

df_fulv = df_drug[df_drug[drug_col] == "Fulvestrant"].copy()
df_fulv = df_fulv[[model_col, drug_col, response_col]].dropna()

models_of_interest = set(df_fulv[model_col].unique())
len(models_of_interest), df_fulv.head()

(965,
         model_id    drug_name   ln_ic50
 69109  SIDM01132  Fulvestrant  2.325255
 69110  SIDM00848  Fulvestrant  2.710606
 69111  SIDM00263  Fulvestrant  2.869553
 69112  SIDM00269  Fulvestrant  2.028349
 69113  SIDM00203  Fulvestrant  3.070346)

In [5]:
# Chunk‑load expression, rename inside each chunk

value_col_original = "rsem_tpm"
##model_col_original = "model_id"
##gene_col_original  = "gene_symbol"

chunks = []
total_rows = 0
kept_rows = 0

for i, chunk in enumerate(pd.read_csv(
    expr_path,
    chunksize=50_000,
    usecols=["model_id", "gene_symbol", value_col_original])):

  # rename columns inside chunk
    chunk = chunk.rename(columns={
        ##model_col_original: "model_id",
        value_col_original: "expr_value",
        ##gene_col_original: "gene_symbol"
    })

    total_rows += len(chunk)

    # filter to models of interest
    chunk = chunk[chunk["model_id"].isin(models_of_interest)]
    kept_rows += len(chunk)

    if not chunk.empty:
        chunks.append(chunk)

    # Progress message every few chunks
    if i % 10 == 0:
        print(f"Chunk {i}: total_rows={total_rows}, kept_rows={kept_rows}")

df_expr_small = pd.concat(chunks, ignore_index=True)
df_expr_small.shape
df_expr_small.head()

Chunk 0: total_rows=50000, kept_rows=22612
Chunk 10: total_rows=550000, kept_rows=248679
Chunk 20: total_rows=1050000, kept_rows=474780
Chunk 30: total_rows=1550000, kept_rows=700911
Chunk 40: total_rows=2050000, kept_rows=927035
Chunk 50: total_rows=2550000, kept_rows=1153098
Chunk 60: total_rows=3050000, kept_rows=1379190
Chunk 70: total_rows=3550000, kept_rows=1605332
Chunk 80: total_rows=4050000, kept_rows=1831440
Chunk 90: total_rows=4550000, kept_rows=2057481
Chunk 100: total_rows=5050000, kept_rows=2283614
Chunk 110: total_rows=5550000, kept_rows=2509731
Chunk 120: total_rows=6050000, kept_rows=2735833
Chunk 130: total_rows=6550000, kept_rows=2961924
Chunk 140: total_rows=7050000, kept_rows=3188044
Chunk 150: total_rows=7550000, kept_rows=3414123
Chunk 160: total_rows=8050000, kept_rows=3640249
Chunk 170: total_rows=8550000, kept_rows=3866329
Chunk 180: total_rows=9050000, kept_rows=4092443
Chunk 190: total_rows=9550000, kept_rows=4318553
Chunk 200: total_rows=10050000, kept_rows=4544614
Chunk 210: total_rows=10550000, kept_rows=4770715
Chunk 220: total_rows=11050000, kept_rows=4996830
Chunk 230: total_rows=11550000, kept_rows=5222964
Chunk 240: total_rows=12050000, kept_rows=5449051
Chunk 250: total_rows=12550000, kept_rows=5675137
Chunk 260: total_rows=13050000, kept_rows=5901232
Chunk 270: total_rows=13550000, kept_rows=6127344
Chunk 280: total_rows=14050000, kept_rows=6353435
Chunk 290: total_rows=14550000, kept_rows=6579523
Chunk 300: total_rows=15050000, kept_rows=6805657
Chunk 310: total_rows=15550000, kept_rows=7031752
Chunk 320: total_rows=16050000, kept_rows=7257850
Chunk 330: total_rows=16550000, kept_rows=7483966
Chunk 340: total_rows=17050000, kept_rows=7710043
Chunk 350: total_rows=17550000, kept_rows=7936184
Chunk 360: total_rows=18050000, kept_rows=8162267
Chunk 370: total_rows=18550000, kept_rows=8388352
Chunk 380: total_rows=19050000, kept_rows=8614462
Chunk 390: total_rows=19550000, kept_rows=8840548
Chunk 400: total_rows=20050000, kept_rows=9066678
Chunk 410: total_rows=20550000, kept_rows=9292777
Chunk 420: total_rows=21050000, kept_rows=9518874
Chunk 430: total_rows=21550000, kept_rows=9744958
Chunk 440: total_rows=22050000, kept_rows=9971083
Chunk 450: total_rows=22550000, kept_rows=10197132
Chunk 460: total_rows=23050000, kept_rows=10423268
Chunk 470: total_rows=23550000, kept_rows=10649393
Chunk 480: total_rows=24050000, kept_rows=10875468
Chunk 490: total_rows=24550000, kept_rows=11101559
Chunk 500: total_rows=25050000, kept_rows=11327660
Chunk 510: total_rows=25550000, kept_rows=11553785
Chunk 520: total_rows=26050000, kept_rows=11779902
Chunk 530: total_rows=26550000, kept_rows=12005974
Chunk 540: total_rows=27050000, kept_rows=12232059
Chunk 550: total_rows=27550000, kept_rows=12458182
Chunk 560: total_rows=28050000, kept_rows=12684260
Chunk 570: total_rows=28550000, kept_rows=12910380
Chunk 580: total_rows=29050000, kept_rows=13136514
Chunk 590: total_rows=29550000, kept_rows=13362601
Chunk 600: total_rows=30050000, kept_rows=13588681
Chunk 610: total_rows=30550000, kept_rows=13814811
Chunk 620: total_rows=31050000, kept_rows=14040899
Chunk 630: total_rows=31550000, kept_rows=14267012
Chunk 640: total_rows=32050000, kept_rows=14493122
Chunk 650: total_rows=32550000, kept_rows=14719196
Chunk 660: total_rows=33050000, kept_rows=14945294
Chunk 670: total_rows=33550000, kept_rows=15171372
Chunk 680: total_rows=34050000, kept_rows=15397526
Chunk 690: total_rows=34550000, kept_rows=15623588
Chunk 700: total_rows=35050000, kept_rows=15849688
Chunk 710: total_rows=35550000, kept_rows=16075767
Chunk 720: total_rows=36050000, kept_rows=16301896
Chunk 730: total_rows=36550000, kept_rows=16528004
Chunk 740: total_rows=37050000, kept_rows=16754108
Chunk 750: total_rows=37550000, kept_rows=16980227
Chunk 760: total_rows=38050000, kept_rows=17206330
Chunk 770: total_rows=38550000, kept_rows=17432434
Chunk 780: total_rows=39050000, kept_rows=17658513
Chunk 790: total_rows=39550000, kept_rows=17884599
Chunk 800: total_rows=40050000, kept_rows=18110724
Chunk 810: total_rows=40550000, kept_rows=18336818
Chunk 820: total_rows=41050000, kept_rows=18562950
Chunk 830: total_rows=41550000, kept_rows=18789017
Chunk 840: total_rows=42050000, kept_rows=19015121
Chunk 850: total_rows=42550000, kept_rows=19241213
Chunk 860: total_rows=43050000, kept_rows=19467328
Chunk 870: total_rows=43550000, kept_rows=19693422
Chunk 880: total_rows=44050000, kept_rows=19921146
Chunk 890: total_rows=44550000, kept_rows=20300111
Chunk 900: total_rows=45050000, kept_rows=20750560
Chunk 910: total_rows=45550000, kept_rows=21250560
Chunk 920: total_rows=46050000, kept_rows=21709438
Chunk 930: total_rows=46550000, kept_rows=22086072
Chunk 940: total_rows=47050000, kept_rows=22544950
Chunk 950: total_rows=47550000, kept_rows=23039142
Chunk 960: total_rows=48050000, kept_rows=23462706
Chunk 970: total_rows=48550000, kept_rows=23921584
Chunk 980: total_rows=49050000, kept_rows=24380462
Chunk 990: total_rows=49550000, kept_rows=24880462
Chunk 1000: total_rows=50050000, kept_rows=25380432
Chunk 1010: total_rows=50550000, kept_rows=25798218
Chunk 1020: total_rows=51050000, kept_rows=26298218
Chunk 1030: total_rows=51550000, kept_rows=26798218
Chunk 1040: total_rows=52050000, kept_rows=27298218
Chunk 1050: total_rows=52550000, kept_rows=27778473
Chunk 1060: total_rows=53050000, kept_rows=28215974
Chunk 1070: total_rows=53550000, kept_rows=28715974
Chunk 1080: total_rows=54050000, kept_rows=29092608
Chunk 1090: total_rows=54550000, kept_rows=29590665
Chunk 1100: total_rows=55050000, kept_rows=29982368
Chunk 1110: total_rows=55550000, kept_rows=30428120
Chunk 1120: total_rows=56050000, kept_rows=30804754
Chunk 1130: total_rows=56550000, kept_rows=31222510
Chunk 1140: total_rows=57050000, kept_rows=31584255
Chunk 1150: total_rows=57550000, kept_rows=31841980
Chunk 1160: total_rows=58050000, kept_rows=32270168
Chunk 1170: total_rows=58550000, kept_rows=32770168
Chunk 1180: total_rows=59050000, kept_rows=33187924
Chunk 1190: total_rows=59550000, kept_rows=33687924
Chunk 1200: total_rows=60050000, kept_rows=34146802
Chunk 1210: total_rows=60550000, kept_rows=34605680
Chunk 1220: total_rows=61050000, kept_rows=35105680
Chunk 1230: total_rows=61550000, kept_rows=35564558
Chunk 1240: total_rows=62050000, kept_rows=36064558
Chunk 1250: total_rows=62550000, kept_rows=36549259
Chunk 1260: total_rows=63050000, kept_rows=37025270
Chunk 1270: total_rows=63550000, kept_rows=37501214
Chunk 1280: total_rows=64050000, kept_rows=37977163
Chunk 1290: total_rows=64550000, kept_rows=38453136
Chunk 1300: total_rows=65050000, kept_rows=38929403
Chunk 1310: total_rows=65550000, kept_rows=39405605
Chunk 1320: total_rows=66050000, kept_rows=39881840
Chunk 1330: total_rows=66550000, kept_rows=40357573
Chunk 1340: total_rows=67050000, kept_rows=40833637
Chunk 1350: total_rows=67550000, kept_rows=41309702
Chunk 1360: total_rows=68050000, kept_rows=41785643
Chunk 1370: total_rows=68550000, kept_rows=42011776
Chunk 1380: total_rows=69050000, kept_rows=42030465
Chunk 1390: total_rows=69550000, kept_rows=42060552
Chunk 1400: total_rows=70050000, kept_rows=42074570
Chunk 1410: total_rows=70550000, kept_rows=42074570
Chunk 1420: total_rows=71050000, kept_rows=42074570
Chunk 1430: total_rows=71550000, kept_rows=42074570
Chunk 1440: total_rows=72050000, kept_rows=42074570
Chunk 1450: total_rows=72550000, kept_rows=42074570
Chunk 1460: total_rows=73050000, kept_rows=42074570
Chunk 1470: total_rows=73550000, kept_rows=42074570
Chunk 1480: total_rows=74050000, kept_rows=42074570
Chunk 1490: total_rows=74550000, kept_rows=42074570
Chunk 1500: total_rows=75050000, kept_rows=42074570
Chunk 1510: total_rows=75550000, kept_rows=42074570
Chunk 1520: total_rows=76050000, kept_rows=42074570
Chunk 1530: total_rows=76550000, kept_rows=42074570
Chunk 1540: total_rows=77050000, kept_rows=42074570
Chunk 1550: total_rows=77550000, kept_rows=42074570
Chunk 1560: total_rows=78050000, kept_rows=42074570
Chunk 1570: total_rows=78550000, kept_rows=42074570

    model_id gene_symbol  expr_value
0  SIDM00776        DVL2      3.5521
1  SIDM00437       STPG1      2.2898
2  SIDM00598       STPG1      2.9486
3  SIDM01070       STPG1      2.4906
4  SIDM00657       STPG1      1.3674

In [6]:
reduced_expr_path = processed_dir / "rnaseq_expression_fulvestrant_models.csv"
df_expr_small.to_csv(reduced_expr_path, index=False)
reduced_expr_path

PosixPath('/content/drive/My Drive/gdsc-drug-response/processed/rnaseq_expression_fulvestrant_models.csv')

In [19]:
df_expr_small = pd.read_csv(processed_dir / "rnaseq_expression_fulvestrant_models.csv")

In [20]:
# Pivot expression to wide format and merge

df_expr_wide = (
    df_expr_small
    .pivot_table(
        index=model_col,
        columns="gene_symbol",
        values="expr_value",
        aggfunc="mean"
    )
    .reset_index()
)

df_expr_wide.shape, df_expr_wide.head()

((940, 41144),
 gene_symbol   model_id    A1BG  A1BG-AS1    A1CF     A2M  A2M-AS1   A2ML1  \
 0            SIDM00003  3.9736    3.1408  0.0144  4.1326   0.4114  0.0000
 1            SIDM00023  0.1110    0.3785  0.2388  0.0286   0.1375  0.0144
 2            SIDM00040  0.0704    0.2016  0.0000  0.2016   0.0841  0.0000
 3            SIDM00041  4.8017    2.9126  0.0286  0.2141   1.7866  0.0286
 4            SIDM00042  0.5059    0.8639  0.0566  0.2265   1.3561  0.4542

 gene_symbol  A2ML1-AS1  A2ML1-AS2   A2MP1  ...    ZXDA    ZXDB    ZXDC  \
 0                  0.0        0.0  0.0000  ...  1.0909  2.1010  4.0488
 1                  0.0        0.0  0.0286  ...  1.5705  2.6323  4.0108
 2                  0.0        0.0  0.0000  ...  0.7655  2.1538  2.4303
 3                  0.0        0.0  0.0144  ...  1.2265  2.0426  4.1152
 4                  0.0        0.0  0.0286  ...  1.2630  2.5008  4.7840

 gene_symbol  ZYG11A  ZYG11AP1  ZYG11B     ZYX  ZYXP1   ZZEF1    ZZZ3
 0            2.6369    0.0976  3.7148  6.9590    0.0  4.3561  5.5622
 1            2.5435    0.0000  3.9439  5.7241    0.0  4.2525  4.5040
 2            2.3813    0.0000  2.7677  5.7477    0.0  2.8718  4.9467
 3            2.4436    0.0566  4.0687  8.4034    0.0  3.9964  5.3740
 4            0.0704    0.0000  2.3813  5.0112    0.0  4.1465  4.2615

 [5 rows x 41144 columns])

In [21]:
# Merge with Fulvestrant response:

df_merged = pd.merge(
    df_fulv,
    df_expr_wide,
    how="inner",
    on=model_col
)

df_merged.shape
df_merged.head()

,model_id,drug_name,ln_ic50,A1BG,A1BG-AS1,A1CF,A2M,A2M-AS1,A2ML1,A2ML1-AS1,...,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11AP1,ZYG11B,ZYX,ZYXP1,ZZEF1,ZZZ3
0,SIDM01132,Fulvestrant,2.325255,5.18545,2.9833,0.0000,0.52325,0.0000,0.0213,0.0000,...,0.31285,1.60475,3.10825,0.6801,0.0,2.58955,5.95435,0.0,3.47415,4.0301
1,SIDM00848,Fulvestrant,2.710606,4.86890,3.4476,0.0000,1.99640,0.1243,3.1890,0.0000,...,1.68260,2.33060,5.18630,0.0841,0.0,3.09930,5.52420,NaN,3.60640,4.5211
2,SIDM00263,Fulvestrant,2.869553,5.03650,3.5558,0.0144,3.98550,0.2987,5.7968,0.0566,...,2.94860,3.39230,6.59630,4.1787,0.0,4.68090,6.37780,0.0,4.57590,5.6946
3,SIDM00269,Fulvestrant,2.028349,4.54970,3.8001,0.0841,3.21570,0.0566,0.5753,0.0000,...,2.82980,3.41280,6.78270,2.3190,0.0,4.21410,9.01050,0.0,4.93400,5.4561
4,SIDM00203,Fulvestrant,3.070346,4.22500,3.2095,0.0144,0.50590,0.0976,2.8156,0.0000,...,2.49570,3.47640,5.30710,3.0321,0.0,4.47310,6.95290,0.0,4.35900,5.3366

In [22]:
# Save for later notebooks:

processed_dir = base_dir / "processed"
processed_dir.mkdir(parents=True, exist_ok=True)

out_path = processed_dir / "fulvestrant_rnaseq_modelready.csv"
print("Saving to:", out_path)
df_merged.to_csv(out_path, index=False)

Saving to: /content/drive/MyDrive/gdsc-drug-response/processed/fulvestrant_rnaseq_modelready.csv